### ISSUE TITLE
Basic authorization stopped working in TeamCity 10

### ISSUE THREAD

**Issue by yaronassa** [acvetkov/teamcity-client#13]
After upgrading to TeamCity 10 every call resulted in 401 unauthorized.
Finally tracked the issue to the basic authorization header you're sending - it's missing the "Basic " prefix.
Changing `authHeader` property to return `{Authorization: "Basic "  + this.auth}` instead of `{Authorization: this.auth}` resolved the issue

**Comment by acvetkov** [comment]
@yaronassa Hi, thank you for issue.

Check out new version
https://www.npmjs.com/package/teamcity-client

Unfortunately, I have no way to check it on Teamcity 10.
Can you test it?

**Comment by yaronassa** [comment]
Works great, thanks for the prompt resolution!

**Comment by acvetkov** [comment]
👍
